(in-package :write-you-a-haskell)

(defparameter *var-a* (make-variable 'a))
(defparameter *var-b* (make-variable 'b))
(defparameter *type-a* (make-type-variable 'a))
(defparameter *type-b* (make-type-variable 'b))
(defparameter *a->a* (make--> *type-a* *type-a*))
(defparameter *a->b* (make--> *type-a* *type-b*))
(defparameter *b=boolean* (singleton-subst *type-b* *boolean*))
(defparameter *a=fixnum* (singleton-subst *type-a* *fixnum*))
(defparameter *identity-function-scheme* (make-forall (list *type-a*) (make--> *type-a* *type-a*)) "forall a. a -> a")
(defparameter *identity-type-scheme* (make-forall (list *type-a*) *type-a*) "forall a. a")
